Blog/blog/models.py
from blog  import db, login_manager 
from datetime import datetime
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(20),unique=True,nullable=False)
    email  = db.Column(db.String(120),unique=True,nullable=False)
    image_file = db.Column(db.String(20),nullable=False,default='default.jpg')
    password = db.Column(db.String(60),nullable=False)
    posts = db.relationship('Post',backref='user',lazy=True)
    comments=db.relationship('Comment',backref='user',lazy=True)

class Post(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(100),nullable=False)
    date_posted = db.Column(db.DateTime(),nullable=False,default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'),nullable=False)
    comments=db.relationship('Comment',backref='post',lazy=True)

class Comment(db.Model):
    id=db.Column(db.Integer,primary_key=True)
    text=db.Column(db.Text,nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'),nullable=False)
    post_id=db.Column(db.Integer,db.ForeignKey('post.id'),nullable=False)

Blog/blog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,BooleanField,TextAreaField
from flask_login import login_user,current_user,logout_user,login_required
from wtforms.validators import DataRequired,Length,Email,EqualTo,ValidationError
from blog.models  import Post,User

class RegistraionForm(FlaskForm):
    username=StringField('Username',validators=[DataRequired(),Length(min=2,max=20)])
    email = StringField('Email',validators=[DataRequired(),Email()])
    password= PasswordField('Password',validators=[DataRequired()])
    confirm_password= PasswordField('Confirm Password',validators=[DataRequired(),EqualTo('password')])
    submit = SubmitField('Sign Up')
    def validate_username(self,username):
        user=User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('UserName is Already Taken')
    def validate_email(self,email):
        user=User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email is Already Taken')
        
class LoginForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    password= PasswordField('Password',validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class UpdateAcountForm(FlaskForm):
    username=StringField('Username',validators=[DataRequired(),Length(min=2,max=20)])
    email = StringField('Email',validators=[DataRequired(),Email()])
    submit = SubmitField('Update')
    def validate_username(self,username):
        if username.data!=current_user.username:
            user=User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('UserName is Already Taken')
    def validate_email(self,email):
        if email.data!=current_user.email:
            user=User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('Email is Already Taken')

Blog/blog/users/routes.py
from flask import render_template, url_for, redirect, flash,request,abort,Blueprint
from flask_login import login_user,current_user,logout_user,login_required
from blog import db,bcrypt
from blog.models import User,Post
from blog.users.forms import RegistraionForm,LoginForm,UpdateAcountForm
users = Blueprint('users',__name__)

@users.route('/register',methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistraionForm()
    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user =User(username=form.username.data,email=form.email.data,password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your Account has been created','success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title="Register", form=form)

@users.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=form.remember.data)
            flash("Logged In Successfuly  ",'success')
            return redirect(url_for('main.home'))
        else:
            flash(f"Unsuccesful Login,Please Enter correct details",'danger')  
    return render_template('login.html', title="Login", form=form)

@users.route('/account', methods=['GET','POST'])
@login_required
def account():
    form = UpdateAcountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Account Deatails are Succesfully Updated","success")
        return redirect(url_for('users.account'))
    elif request.method=='GET':
        form.username.data=current_user.username
        form.email.data=current_user.email
    image_file = url_for('static',filename='profile_pics/'+current_user.image_file)
    return render_template('account.html',title="Account",image_file=image_file,form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged Out Succesfully','success')
    return redirect(url_for('main.home'))

Blog/blog/templates/about.html
{% extends 'layout.html' %}
{% block content %}
    <h1>This is a about page</h1>
{% endblock content%}

Blog/blog/templates/account.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img src={{ image_file }} class="rounded-circle account-img">
            <div class="media-body">
                <h2>{{ current_user.username }}</h2>
                <p>{{ current_user.email }}</p>
            </div>
        </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom text-center">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}   
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content%}

Blog/blog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom text-center">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control is-invalid") }}   
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

Blog/blog/templates/home.html
{% extends 'layout.html' %}
{% block content%}
    {% for post in posts %}
        <article class="media content-section">
            <img src="{{ url_for('static',filename='profile_pics/'+post.user.image_file)}}" alt="" class="rounded-circle article-img">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2 mt-2" href="{{ url_for('posts.user_info',post_id=post.id)}}"class="btn btn-secondary btn-sm ml-2">{{ post.user.username }}</a>
                    <small class="text-muted">{{ post.date_posted }}</small>
                </div>  
                <h2><a class="article-title" href="{{ url_for('posts.post',post_id=post.id)}}">{{ post.title }}</a></h2>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

    

Blog/blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% if title %}
    <title>Flask-Blog-{{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
  <header class="site-header" >
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/home">CrickBlog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <!-- <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li> -->
          {% if current_user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="/post/new">New Post</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="/account">profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/logout">Logout</a>
            </li>
          {% else%}
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="/register">Regsiter</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=True)%}
          {% if messages %}
            {% for category,message in messages %}
              <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Quick Links</h3>
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Latest Posts</li>
              <li class="list-group-item list-group-item-light">Announcements</li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

Blog/blog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom text-center">Login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}   
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{form.remember(class="form-check-input")}}
                    {{form.remember.label(class="form-check-label")}}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Regsister Now</a>
        </small>
    </div>
{% endblock content %}

Blog/blog/templates/post.html
{% extends 'layout.html' %}
{% block content%}
<article class="media content-section">
    <img src="{{ url_for('static',filename='profile_pics/'+post.user.image_file)}}" alt="" class="rounded-circle article-img">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2 mt-2" href="{{ url_for('posts.user_info',post_id=post.id)}}"class="btn btn-secondary btn-sm ml-2">{{ post.user.username }}</a>
            <small class="text-muted">{{ post.date_posted }}</small>
            {% if post.user==current_user %}
                <a href="{{ url_for('posts.update_post',post_id=post.id)}}" class="btn btn-secondary btn-sm m-2">Update</a>
                <a href="{{ url_for('posts.delete_post',post_id=post.id)}}" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-danger btn-sm m-2">Delete</a>
            {% endif %}
        </div>  
        <span class="badge badge-info">Title</span><h2 class="article-title">{{ post.title }}</h2>
        <span class="badge badge-info">Content</span>
        <p class="article-content">{{ post.content }}</p>
        <h5><span class="badge badge-info">Comments</span></h5>
        <hr>
        <div class="content-section">
            {% for comment in post.comments %}
                <div class="media">
                    <img src={{ image_file }} class="rounded account-image">
                    <div class="media-body">
                        <a class="mr-2 mt-2" href="{{ url_for('posts.user_info',post_id=post.id)}}"class="btn btn-secondary btn-sm ml-2">{{ comment.user.username }}</a>
                        <p>{{ comment.text }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div>
        <hr>
        {% if current_user.is_authenticated %}
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom">Leave a Comment</legend>
                        <div class="form-group">
                            {{ form.text.label(class="form-control-label") }}
                            {% if form.text.errors %}
                                {{ form.text(class="form-control is-invalid") }}   
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.text(class="form-control") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
        {% else %}
            <small>Login to Leave a Comment</small>
        {% endif %}
    </div>
</article>
{% endblock content %}

    

Blog/blog/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom text-center">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}   
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control")}}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

Blog/blog/templates/user_info.html
{% extends 'layout.html' %}
{% block content%}
    <div class="content-section">
        <div class="media">
            <img src={{ image_file }} class="rounded-circle account-img">
            <div class="media-body">
                <h2>{{ post.user.username }}</h2>
                <p>{{ post.user.email }}</p>
            </div>
        </div>
    </div>
    <div>
        <h2><span class="badge badge-info">posts</span></h2>
    </div>
    {% for post in post.user.posts %}
        <article class="media content-section">
            <!-- <img src="{{ url_for('static',filename='profile_pics/'+post.user.image_file)}}" alt="" class="rounded-circle article-img"> -->
            <div class="media-body">
                <div class="article-metadata">
                    <small class="text-muted">{{ post.date_posted }}</small>
                </div>  
            <h2><a class="article-title" href="{{ url_for('posts.post',post_id=post.id)}}">{{ post.title }}</a></h2> 
                
            </div>
        </article>
    {% endfor %}
{% endblock content %}